### Busqueda de administradores con paginacion
GET http://localhost:8080/administrators/pagina/0
Accept: application/json

### Agregado de administrador
POST http://localhost:8080/administrators
Content-Type: application/json

{
  "nombre": "Ruben ggg",
  "apellido": "Diaz",
  "fecha_nacimiento": "1999-5-5",
  "usuario": "Ruco",
  "password": "contra"
}

### Modificar administrador
PUT http://localhost:8080/administrators/2
Content-Type: application/json

{
  "nombre": "Roberto",
  "apellido": "Melendez",
  "fecha_nacimiento": "1999-5-5",
  "usuario": "Robert",
  "password": "4050"
}

### Eliminado logico
PUT http://localhost:8080/administrators/delete/2

### Eliminado fisico
DELETE http://localhost:8080/administrators/2

### Busqueda de administrador por id
GET http://localhost:8080/administrators/4